apiVersion: apps/v1
kind: Deployment
metadata:
  name: hp-vol-myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hp-myapp
  template:
    metadata:
      labels:
        app: hp-myapp
    spec:
      volumes:
        - name: hp-vol
          hostPath:
            path: /opt/host_share
      containers:
      - name: cont1
        image: nginx
        resources:
        ports:
        - containerPort: 80
        volumeMounts:
          - name: hp-vol
            mountPath: /usr/share/nginx/html
