kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-vol-dep
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: nfspvhpapp
  template:
    metadata:
      labels:
        role: nfspvhpapp
    spec:
      terminationGracePeriodSeconds: 0
      restartPolicy: Always
      volumes:
        - name: pv-vol
          #emptyDir: {}
          #hostPath:
          #  path: /opt/config  ### this is the path on vm / wnode wherever the pod will be created
          persistentVolumeClaim:
            claimName: nfs-pvc
      containers:
        - name: cont1
          image: nginx
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: pv-vol
              mountPath: /usr/share/nginx/html   ## is the path inside container
      resources:
