kind: Deployment
apiVersion: apps/v1
metadata:
  name: dep1
spec:
  replicas: 10
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      nodeName: worker1 # use this only when you want the pod to be run on a specific node
      containers:
      - name: conty
        image: leaddevops/kubeserve:v1
        resources:
        ports:
        - name: http
          containerPort: 80
