kind: Pod
apiVersion: v1
metadata:
  name: pod2
  labels:
    team: pggroup
spec:
  containers:
    - name: cont1
      image: nginx
      ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
