apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      volumes:
        - name: demo-vol
          emptyDir: {}
      containers:
      - name: cont1
        image: nginx
        resources:
        ports:
        - containerPort: 80
        volumeMounts:
          - name: demo-vol
            mountPath: /usr/share/nginx/html
      - name: cont2
        image: centos
        command: [ "bash", "-c", "echo hi there from cont2 > /opt/riyer/index.html ; sleep 3600"]
        resources:
        volumeMounts:
          - name: demo-vol
            mountPath: /usr/share/nginx/html

