kind: Pod ## kubectl api-resources
apiVersion: v1
metadata:
  name: project2-multi-pod
  labels:
    project: p2
spec:
  containers:
    - name: cont1
      image: nginx
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      ports:
        - name: http
          containerPort: 80
    - name: cont2
      image: debian
      volumeMounts:
      - name: html
        mountPath: /html
      command: ["/bin/sh", "-c"]
      args:
        - while true; do
            date >> /html/index.html;
            sleep 1;
          done