kind: Deployment
apiVersion: apps/v1
metadata:
  name: sec-dep
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      role: cmapp
  template:
    metadata:
      labels:
        role: cmapp
    spec:
      terminationGracePeriodSeconds: 0
      restartPolicy: Always
      volumes:
        - name: sec-vol
          secret:
            secretName: my-secret
      containers:
        - name: cont1
          image: nginx
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: sec-vol
              mountPath: /secconfig   ## is the path inside container
          envFrom:
           - secretRef:
               name: test-secret
          resources:
